{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-redis
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: {{ .Values.redis.strategy.type | default "Recreate" }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "paperless-ngx.name" . }}-redis
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "paperless-ngx.name" . }}-redis
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          command: ["/bin/sh","-c"]
          args:
            - |
              chown -R redis:redis /data 2>/dev/null || true
              exec docker-entrypoint.sh redis-server
          ports:
            - containerPort: {{ .Values.redis.service.port }}
              name: tcp-redis
          volumeMounts:
            {{- if .Values.redis.persistence.enabled }}
            - name: data
              mountPath: /data
            {{- end }}
          {{- with .Values.redis.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.redis.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "paperless-ngx.claimName" (list . "redis" .Values.redis.persistence) }}
      {{- end }}
{{- end }}
