{{- if .Values.tika.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-tika
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: {{ .Values.tika.strategy.type | default "Recreate" }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "paperless-ngx.name" . }}-tika
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "paperless-ngx.name" . }}-tika
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: tika
          image: "{{ .Values.tika.image.repository }}:{{ .Values.tika.image.tag }}"
          imagePullPolicy: {{ .Values.tika.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.tika.service.port }}
              name: http-tika
          {{- with .Values.tika.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
